blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', views.PostListView.as_view(), name='post_list'),
    # path('blog/', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',
         views.post_detail, name='post_detail'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.my_login, name='my_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('dashboard/<int:id>/', views.dashboard, name='dashboard'),
    path('<int:post_id>/like/', views.like_post, name='like_post'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
            .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    img = models.ImageField(upload_to='images/', blank=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    likes = models.ManyToManyField(
        User, through='Like', related_name='liked_post', blank=True)
    comments = models.ManyToManyField(
        User, through='Comment', related_name='commented_post', blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug
        ])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.user.first_name} - {self.post.title}"


class Like(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.user.first_name} - {self.post.title}"

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class CreateUserForm(UserCreationForm):
    username = forms.CharField(max_length=255, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control form-icon-input',
               'placeholder': 'username'}
    ))
    first_name = forms.CharField(max_length=255, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control form-icon-input',
               'placeholder': 'Ism', 'type': 'text'}
    ))
    last_name = forms.CharField(max_length=255, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control form-icon-input',
               'placeholder': 'Familiya', 'type': 'text'}
    ))
    password1 = forms.CharField(max_length=255, required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control form-icon-input',
               'placeholder': 'Parol', 'type': 'password'}
    ))
    password2 = forms.CharField(max_length=255, required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control form-icon-input',
               'placeholder': 'Parolni tasdiqlash', 'type': 'password'}
    ))

    class Meta(UserCreationForm):
        model = User
        fields = ['username', 'first_name',
                  'last_name', 'password1', 'password2']


class LoginForm(forms.Form):
    username = forms.CharField(max_length=255, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control form-icon-input',
               'placeholder': 'username'}
    ))
    password = forms.CharField(max_length=255, required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control form-icon-input',
               'placeholder': 'Parol', 'type': 'password'}
    ))

blog/views.py
from django.http import Http404
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Like, Comment
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.views.generic import ListView, CreateView
from django.core.paginator import Paginator
from .forms import CreateUserForm, LoginForm, CommentForm
from django.contrib.auth.decorators import login_required


class SignUpView(CreateView):
    form_class = CreateUserForm
    success_url = reverse_lazy('blog:my_login')
    template_name = 'registration/signup.html'


def my_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('blog:home')

    else:
        form = LoginForm()

    data = {
        'form': form,
    }

    return render(request, 'registration/login.html', data)


def home(request):
    return render(request, 'blog/home.html')


def user_logout(request):
    logout(request)
    return redirect('blog:home')


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 4
    template_name = 'blog/post/list.html'


# def post_list(request):
#     post_list = Post.published.all()
#     paginitor = Paginator(post_list, 4)
#     page_number = request.GET.get('page', 1)
#     try:
#         posts = paginitor.page(page_number)
#     except:
#         posts = paginitor.page(1)

#     return render(request,
#                   'blog/post/list.html',
#                   {'posts': posts})


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=slug,
        publish__year=year,
        publish__month=month,
        publish__day=day
    )
    comments = Comment.objects.filter(post=post)
    likes = Like.objects.filter(post=post)

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.author = request.user
            new_comment.save()
            return redirect('blog:post_detail', year=year, month=month, day=day, slug=slug)
    else:
        comment_form = CommentForm()

    data = {
        'post': post,
        'likes': likes,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'blog/post/detail.html', data)


def like_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    liked, created = Like.objects.get_or_create(post=post, user=request.user)

    if not created:
        liked.delete()

    likes_count = post.likes.count()

    return JsonResponse({'likes_count': likes_count})


@login_required
def dashboard(request, id):
    if request.user.id == id:
        user = get_object_or_404(User, id=id)

        data = {
            'user': user
        }
        return render(request, 'dashboard.html', data)
    else:
        return redirect("blog:home")

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>

    <div class="container">
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
                <div class="col-4 pt-1">
                    <a class="text-dark" href="/">Home</a>
                </div>
                {% if not request.user.is_authenticated %}
                <div class="col-md-3">
                    <a href="{% url 'blog:my_login' %}" type="button" class="btn btn-outline-primary me-2">Kirish</a>
                    <a href="{% url 'blog:signup' %}" type="button" class="btn btn-primary">Ro'yxatdan o'tish</a>
                </div>
                {% else %}
                <div class="col-md-3">
                    <div class="dropdown text-end">
                        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="https://e7.pngegg.com/pngimages/799/987/png-clipart-computer-icons-avatar-icon-design-avatar-heroes-computer-wallpaper-thumbnail.png"
                                alt="mdo" width="32" height="32" class="rounded-circle">
                        </a>
                        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                            <div class="m-3">
                                <p>
                                    {{ request.user.first_name }}
                                    {{ request.user.last_name }}
                                </p>
                            </div>
                            <li><a class="dropdown-item" href="#">New project...</a></li>
                            <li><a class="dropdown-item" href="{% url 'blog:dashboard' request.user.id %}">Profile</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'blog:user_logout' %}">Sign out</a></li>
                        </ul>
                    </div>
                </div>
                {% endif %}
            </div>
        </header>
    </div>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/blog/home.html
{% extends "blog/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}

<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h4 class="display-6">Blog Home page</h4>
        <a href="{% url 'blog:post_list' %}" class="btn btn-primary btn-lg" type="button">Our Blogs</a>
    </div>
</div>

{% endblock %}

templates/blog/paginiton.html
{% if page.has_other_pages %}
<nav aria-label="Page navigation example">
    <ul class="pagination">

        {% if page.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Previous</a></li>
        {% else %}
        <li class="page-item disabled"></li>
        {% endif %}

        {% for i in page.paginator.page_range %}
        {% if page.number == i %}
        <li class="page-item disabled"><a class="page-link">{{ i }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}

        {% if page.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">Next</a></li>
        {% else %}
        <li class="page-item disabled"></li>
        {% endif %}
    </ul>
</nav>
{% endif %}