blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', views.PostListView.as_view(), name='post_list'),
    # path('blog/', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',
         views.post_detail, name='post_detail'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.my_login, name='my_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('dashboard/<int:id>/', views.dashboard, name='dashboard'),
    path('<int:post_id>/like/', views.like_post, name='like_post'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
            .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    img = models.ImageField(upload_to='images/', blank=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    likes = models.ManyToManyField(
        User, through='Like', related_name='liked_post', blank=True)
    comments = models.ManyToManyField(
        User, through='Comment', related_name='commented_post', blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug
        ])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.user.first_name} - {self.post.title}"


class Like(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.user.first_name} - {self.post.title}"

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class CreateUserForm(UserCreationForm):
    username = forms.CharField(max_length=255, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control form-icon-input',
               'placeholder': 'username'}
    ))
    first_name = forms.CharField(max_length=255, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control form-icon-input',
               'placeholder': 'Ism', 'type': 'text'}
    ))
    last_name = forms.CharField(max_length=255, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control form-icon-input',
               'placeholder': 'Familiya', 'type': 'text'}
    ))
    password1 = forms.CharField(max_length=255, required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control form-icon-input',
               'placeholder': 'Parol', 'type': 'password'}
    ))
    password2 = forms.CharField(max_length=255, required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control form-icon-input',
               'placeholder': 'Parolni tasdiqlash', 'type': 'password'}
    ))

    class Meta(UserCreationForm):
        model = User
        fields = ['username', 'first_name',
                  'last_name', 'password1', 'password2']


class LoginForm(forms.Form):
    username = forms.CharField(max_length=255, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control form-icon-input',
               'placeholder': 'username'}
    ))
    password = forms.CharField(max_length=255, required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control form-icon-input',
               'placeholder': 'Parol', 'type': 'password'}
    ))

blog/views.py
from django.http import Http404
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Like, Comment
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.views.generic import ListView, CreateView
from django.core.paginator import Paginator
from .forms import CreateUserForm, LoginForm, CommentForm
from django.contrib.auth.decorators import login_required


class SignUpView(CreateView):
    form_class = CreateUserForm
    success_url = reverse_lazy('blog:my_login')
    template_name = 'registration/signup.html'


def my_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('blog:home')

    else:
        form = LoginForm()

    data = {
        'form': form,
    }

    return render(request, 'registration/login.html', data)


def home(request):
    return render(request, 'blog/home.html')


def user_logout(request):
    logout(request)
    return redirect('blog:home')


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 4
    template_name = 'blog/post/list.html'


# def post_list(request):
#     post_list = Post.published.all()
#     paginitor = Paginator(post_list, 4)
#     page_number = request.GET.get('page', 1)
#     try:
#         posts = paginitor.page(page_number)
#     except:
#         posts = paginitor.page(1)

#     return render(request,
#                   'blog/post/list.html',
#                   {'posts': posts})


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=slug,
        publish__year=year,
        publish__month=month,
        publish__day=day
    )
    comments = Comment.objects.filter(post=post)
    likes = Like.objects.filter(post=post)

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.author = request.user
            new_comment.save()
            return redirect('blog:post_detail', year=year, month=month, day=day, slug=slug)
    else:
        comment_form = CommentForm()

    data = {
        'post': post,
        'likes': likes,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'blog/post/detail.html', data)


def like_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    liked, created = Like.objects.get_or_create(post=post, user=request.user)

    if not created:
        liked.delete()

    likes_count = post.likes.count()

    return JsonResponse({'likes_count': likes_count})


@login_required
def dashboard(request, id):
    if request.user.id == id:
        user = get_object_or_404(User, id=id)

        data = {
            'user': user
        }
        return render(request, 'dashboard.html', data)
    else:
        return redirect("blog:home")

templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}

<div class="row g-5">
    <div class="col-md-8">
        <article class="blog-post">
            {% if post.img %}
            <div>
                <img src="{{ post.img.url }}" class="card-img-top" alt="{{ post.title }}">
            </div>
            {% endif %}
            <h2 class="blog-post-title">{{ post.title }}</h2>
            <p class="blog-post-meta">{{ post.publish }} by <a href="#">{{ post.author }}</a></p>
            <p id="likes-count">
                {{ likes.count }} Likes
                {% if request.user.is_authenticated %}
                <button id="like-button" class="ms-5">
                    <i class="bi bi-heart-fill"></i>
                </button>
                {% endif %}
            </p>

            <hr>
            <p>
                {{ post.body }}
            </p>
            {% if comments %}
            <h5>Comments:</h5>
            {% for comment in comments %}
            <p>
                {{ comment.author.first_name }}: {{ comment.text }}
            </p>
            {% endfor %}
            <br><br>
            {% endif %}
        </article>
        {% if request.user.is_authenticated %}
        <div class="container">
            <form method="post" action="">
                {% csrf_token %}
                {{ comment_form }}

                <button type="submit">Jo'natish</button>
            </form>
        </div>
        {% endif %}

        <nav class="blog-pagination mb-5" aria-label="Pagination">
            <a class="btn btn-outline-primary" href="{% url 'blog:post_list' %}">Orqaga</a>
        </nav>

    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const likeButton = document.getElementById('like-button');
        const likesCount = document.getElementById('likes-count');

        likeButton.addEventListener('click', function () {
            fetch('{% url "blog:like_post" post.id %}', {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                },
            })
                .then(response => response.json())
                .then(data => {
                    likesCount.textContent = data.likes_count + ' Likes';
                });
        });
    });
</script>

{% endblock %}

templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}

<div class="row mb-2">
    {% for post in posts %}
    <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary">NEW</strong>
                {% if post.img %}
                <div>
                    <img src="{{ post.img.url }}" class="rounded-3" width="240" height="164" alt="{{ post.title }}">
                </div>
                {% endif %}
                <h5 class="mb-0">{{ post.title|truncatewords:8 }}</h5>
                <div class="mb-1 text-muted">{{ post.publish }}</div>
                <p class="card-text mb-auto">
                    {{ post.body|truncatewords:20 }}
                </p>
                <a href="{{ post.get_absolute_url }}" class="stretched-link">Continue reading</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% include 'blog/paginiton.html' with page=page_obj %}

{% endblock %}