blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', views.PostListView.as_view(), name='post_list'),
    # path('blog/', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',
         views.post_detail, name='post_detail'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.my_login, name='my_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('dashboard/<int:id>/', views.dashboard, name='dashboard'),
    path('<int:post_id>/like/', views.like_post, name='like_post'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/dashboard.html
{% extends "blog/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}

<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h4 class="display-6">Dashboard</h4>
        <p>{{ user.first_name }} {{ user.last_name }}
            {% if user.email %}
            - {{ user.email }}
            {% endif %}
        </p>
        <a href="{% url 'blog:home' %}" class="btn btn-primary btn-lg" type="button">Home</a>
    </div>
</div>

{% endblock %}